api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'bestiary', views.MonsterViewSet)
router.register(r'skill', views.MonsterSkillViewSet)
router.register(r'skill_effect', views.MonsterSkillEffectViewSet)
router.register(r'leader_skill', views.MonsterLeaderSkillViewSet)
router.register(r'source', views.MonsterSourceViewSet)

urlpatterns = [
    # REST framework stuff
    url(r'^', include(router.urls)),

    # Custom API stuff
    url(r'bestiary/(?P<pk>[0-9]+)/chart/$', views.bestary_stat_charts, name='bestiary_stat_chart'),
]

news/urls.py
from django.conf.urls import url

from . import views

app_name = 'news'

urlpatterns = [
    # Main landing page
    url(r'^$', views.latest_news, name='latest_news'),
]

swarfarm/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles import views
from bestiary.autocomplete import *

urlpatterns = [
    # AJAX-y stuff first
    url(r'^autocomplete/', include([
        url(r'^bestiary/$', BestiaryAutocomplete.as_view(), name='bestiary-monster-autocomplete'),
        url(r'^quick-search/$', QuickSearchAutocomplete.as_view(), name='bestiary-quicksearch-autocomplete'),
    ])),
    url(r'^api/v2/', include('apiv2.urls', namespace='v2')),
    url(r'^api/', include('api.urls')),
    url(r'^api(/v\d+)?/auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Bestiary
    url(r'^bestiary/', include('bestiary.urls', namespace='bestiary')),

    # SWARFARM app
    url(r'^', include('news.urls', namespace='news')),

    # Django auth/admin stuff
    url('admin/clearcache/', include('clearcache.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

news/models.py
from django.db import models
from django.utils import timezone


class Article(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    sticky = models.BooleanField(default=False)
    highlight = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-sticky', '-created')

news/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Article


def latest_news(request):
    news_posts = Article.objects.all()

    paginator = Paginator(news_posts, 5)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'page_range': paginator.page_range,
    }

    return render(request, 'news/latest_news.html', context)


def post(request, article_id):
    article = get_object_or_404(Article, pk=article_id)

    return render(request, 'news/article.html', {'article': article})

news/templates/news/latest_news.html
{% extends 'base.html' %}
{% load cache %}
{% load markdown_deux_tags %}

{% block content %}
    {% cache 60 latest_news posts.number %}
        {% for post in posts %}
            <div class="card {% if not post.highlight %}border-0{% else %}border-danger{% endif %} shadow mb-3" >
                <div class="card-header bg-white">
                    {% if post.sticky %}<i class="fas fa-thumbtack patreon"></i>&nbsp;{% endif %}<small class="fw-lighter fs-5">{{ post.created|date:"DATE_FORMAT" }}</small>
                </div>
                <div class="card-body">
                    <h1 class="card-title fw-lighter">{{ post.title }}</h1>
                    {{ post.body|markdown }}
                </div>
            </div>
        {% empty %}
            <p>No news!</p>
        {% endfor %}

        <nav>
            <ul class="pagination">
                {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link border-0 pager-btn bg-white" href="?page={{ posts.previous_page_number }}">
                            <span>&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link border-0 pager-btn bg-white" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for page_num in page_range %}
                    <li class="page-item">
                        <a class="page-link border-0 pager-btn bg-white{% if page_num == posts.number %} active{% endif %}" href="{% url 'news:latest_news' %}?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endfor %}

                {% if posts.has_next %}
                    <li class="page-item">
                        <a class=" page-link border-0 pager-btn bg-white" href="?page={{ posts.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class=" page-link border-0 pager-btn bg-white" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endcache %}
{% endblock content %}