api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'bestiary', views.MonsterViewSet)
router.register(r'skill', views.MonsterSkillViewSet)
router.register(r'skill_effect', views.MonsterSkillEffectViewSet)
router.register(r'leader_skill', views.MonsterLeaderSkillViewSet)
router.register(r'source', views.MonsterSourceViewSet)

urlpatterns = [
    # REST framework stuff
    url(r'^', include(router.urls)),

    # Custom API stuff
    url(r'bestiary/(?P<pk>[0-9]+)/chart/$', views.bestary_stat_charts, name='bestiary_stat_chart'),
]

bestiary/urls.py
from django.urls import path, include

from . import views

app_name = 'bestiary'

urlpatterns = [
    path('', views.bestiary, name='home'),
    path('inventory/', views.bestiary_inventory, name='inventory'),
    path('<slug:monster_slug>/', views.bestiary_detail, name='detail'),
]

swarfarm/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles import views
from bestiary.autocomplete import *

urlpatterns = [
    # AJAX-y stuff first
    url(r'^autocomplete/', include([
        url(r'^bestiary/$', BestiaryAutocomplete.as_view(), name='bestiary-monster-autocomplete'),
        url(r'^quick-search/$', QuickSearchAutocomplete.as_view(), name='bestiary-quicksearch-autocomplete'),
    ])),
    url(r'^api/v2/', include('apiv2.urls', namespace='v2')),
    url(r'^api/', include('api.urls')),
    url(r'^api(/v\d+)?/auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Bestiary
    url(r'^bestiary/', include('bestiary.urls', namespace='bestiary')),

    # SWARFARM app
    url(r'^', include('news.urls', namespace='news')),

    # Django auth/admin stuff
    url('admin/clearcache/', include('clearcache.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

bestiary/models.py
from collections import OrderedDict
from functools import partial
from itertools import zip_longest
from math import floor
from operator import is_not

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.safestring import mark_safe
from django.utils.text import slugify


class Monster(models.Model):
    ELEMENT_PURE = 'pure'
    ELEMENT_FIRE = 'fire'
    ELEMENT_WIND = 'wind'
    ELEMENT_WATER = 'water'
    ELEMENT_LIGHT = 'light'
    ELEMENT_DARK = 'dark'

    TYPE_ATTACK = 'attack'
    TYPE_HP = 'hp'
    TYPE_SUPPORT = 'support'
    TYPE_DEFENSE = 'defense'
    TYPE_MATERIAL = 'material'
    TYPE_NONE = 'none'

    ELEMENT_CHOICES = (
        (ELEMENT_PURE, 'Pure'),
        (ELEMENT_FIRE, 'Fire'),
        (ELEMENT_WIND, 'Wind'),
        (ELEMENT_WATER, 'Water'),
        (ELEMENT_LIGHT, 'Light'),
        (ELEMENT_DARK, 'Dark'),
    )

    TYPE_CHOICES = (
        (TYPE_NONE, 'None'),
        (TYPE_ATTACK, 'Attack'),
        (TYPE_HP, 'HP'),
        (TYPE_SUPPORT, 'Support'),
        (TYPE_DEFENSE, 'Defense'),
        (TYPE_MATERIAL, 'Material'),
    )

    STAR_CHOICES = (
        (1, mark_safe('1<span class="glyphicon glyphicon-star"></span>')),
        (2, mark_safe('2<span class="glyphicon glyphicon-star"></span>')),
        (3, mark_safe('3<span class="glyphicon glyphicon-star"></span>')),
        (4, mark_safe('4<span class="glyphicon glyphicon-star"></span>')),
        (5, mark_safe('5<span class="glyphicon glyphicon-star"></span>')),
        (6, mark_safe('6<span class="glyphicon glyphicon-star"></span>')),
    )

    AWAKEN_LEVEL_INCOMPLETE = -1  # Japan fusion
    AWAKEN_LEVEL_UNAWAKENED = 0
    AWAKEN_LEVEL_AWAKENED = 1
    AWAKEN_LEVEL_SECOND = 2

    AWAKEN_CHOICES = (
        (AWAKEN_LEVEL_UNAWAKENED, 'Unawakened'),
        (AWAKEN_LEVEL_AWAKENED, 'Awakened'),
        (AWAKEN_LEVEL_SECOND, 'Second Awakening'),
        (AWAKEN_LEVEL_INCOMPLETE, 'Incomplete'),
    )

    # Mappings from com2us' API data to model defined values
    COM2US_ELEMENT_MAP = {
        1: ELEMENT_WATER,
        2: ELEMENT_FIRE,
        3: ELEMENT_WIND,
        4: ELEMENT_LIGHT,
        5: ELEMENT_DARK,
        6: ELEMENT_PURE,
    }

    COM2US_ARCHETYPE_MAP = {
        0: TYPE_NONE,
        1: TYPE_ATTACK,
        2: TYPE_DEFENSE,
        3: TYPE_HP,
        4: TYPE_SUPPORT,
        5: TYPE_MATERIAL
    }

    COM2US_AWAKEN_MAP = {
        -1: AWAKEN_LEVEL_INCOMPLETE,
        0: AWAKEN_LEVEL_UNAWAKENED,
        1: AWAKEN_LEVEL_AWAKENED,
        2: AWAKEN_LEVEL_SECOND,
    }

    name = models.CharField(max_length=40)
    com2us_id = models.IntegerField(blank=True, null=True, help_text='ID given in game data files')
    family_id = models.IntegerField(blank=True, null=True, help_text='Identifier that matches same family monsters')
    image_filename = models.CharField(max_length=250, null=True, blank=True)
    element = models.CharField(max_length=6, choices=ELEMENT_CHOICES, default=ELEMENT_FIRE)
    archetype = models.CharField(max_length=10, choices=TYPE_CHOICES, default=TYPE_ATTACK)
    base_stars = models.IntegerField(choices=STAR_CHOICES, help_text='Display stars in game')
    natural_stars = models.IntegerField(choices=STAR_CHOICES, help_text="Stars of the monster's lowest awakened form")
    obtainable = models.BooleanField(default=True, help_text='Is available for players to acquire')
    can_awaken = models.BooleanField(default=True, help_text='Has an awakened form')
    is_awakened = models.BooleanField(default=False, help_text='Is the awakened form')
    awaken_level = models.IntegerField(default=AWAKEN_LEVEL_UNAWAKENED, choices=AWAKEN_CHOICES, help_text='Awakening level')
    awaken_bonus = models.TextField(blank=True, help_text='Bonus given upon awakening')

    skills = models.ManyToManyField('Skill', blank=True)
    skill_ups_to_max = models.IntegerField(null=True, blank=True, help_text='Number of skill-ups required to max all skills')
    leader_skill = models.ForeignKey('LeaderSkill', on_delete=models.SET_NULL, null=True, blank=True)

    # 1-star lvl 1 values from data source
    raw_hp = models.IntegerField(null=True, blank=True, help_text='HP value from game data files')
    raw_attack = models.IntegerField(null=True, blank=True, help_text='ATK value from game data files')
    raw_defense = models.IntegerField(null=True, blank=True, help_text='DEF value from game data files')

    # Base-star lvl MAX values as seen in-game
    base_hp = models.IntegerField(null=True, blank=True, help_text='HP at base_stars lvl 1')
    base_attack = models.IntegerField(null=True, blank=True, help_text='ATK at base_stars lvl 1')
    base_defense = models.IntegerField(null=True, blank=True, help_text='DEF at base_stars lvl 1')

    # 6-star lvl MAX values
    max_lvl_hp = models.IntegerField(null=True, blank=True, help_text='HP at 6-stars lvl 40')
    max_lvl_attack = models.IntegerField(null=True, blank=True, help_text='ATK at 6-stars lvl 40')
    max_lvl_defense = models.IntegerField(null=True, blank=True, help_text='DEF at 6-stars lvl 40')

    speed = models.IntegerField(null=True, blank=True)
    crit_rate = models.IntegerField(null=True, blank=True)
    crit_damage = models.IntegerField(null=True, blank=True)
    resistance = models.IntegerField(null=True, blank=True)
    accuracy = models.IntegerField(null=True, blank=True)

    # Homunculus monster fields
    homunculus = models.BooleanField(default=False)
    craft_materials = models.ManyToManyField('CraftMaterial', through='MonsterCraftCost')
    craft_cost = models.IntegerField(null=True, blank=True, help_text='Mana cost to craft this monster')

    # Unicorn fields
    transforms_into = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='+', help_text='Monster which this monster can transform into during battle')

    awakens_from = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='+', help_text='Unawakened form of this monster')
    awakens_to = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='+', help_text='Awakened form of this monster')
    awaken_mats_fire_low = models.IntegerField(blank=True, default=0)
    awaken_mats_fire_mid = models.IntegerField(blank=True, default=0)
    awaken_mats_fire_high = models.IntegerField(blank=True, default=0)
    awaken_mats_water_low = models.IntegerField(blank=True, default=0)
    awaken_mats_water_mid = models.IntegerField(blank=True, default=0)
    awaken_mats_water_high = models.IntegerField(blank=True, default=0)
    awaken_mats_wind_low = models.IntegerField(blank=True, default=0)
    awaken_mats_wind_mid = models.IntegerField(blank=True, default=0)
    awaken_mats_wind_high = models.IntegerField(blank=True, default=0)
    awaken_mats_light_low = models.IntegerField(blank=True, default=0)
    awaken_mats_light_mid = models.IntegerField(blank=True, default=0)
    awaken_mats_light_high = models.IntegerField(blank=True, default=0)
    awaken_mats_dark_low = models.IntegerField(blank=True, default=0)
    awaken_mats_dark_mid = models.IntegerField(blank=True, default=0)
    awaken_mats_dark_high = models.IntegerField(blank=True, default=0)
    awaken_mats_magic_low = models.IntegerField(blank=True, default=0)
    awaken_mats_magic_mid = models.IntegerField(blank=True, default=0)
    awaken_mats_magic_high = models.IntegerField(blank=True, default=0)

    source = models.ManyToManyField('Source', blank=True, help_text='Where this monster can be acquired from')
    farmable = models.BooleanField(default=False, help_text='Monster can be acquired easily without luck')
    fusion_food = models.BooleanField(default=False, help_text='Monster is used as a fusion ingredient')
    bestiary_slug = models.SlugField(max_length=255, editable=False, null=True)

    def image_url(self):
        if self.image_filename:
            return mark_safe('<img src="%s" height="42" width="42"/>' % static('herders/images/monsters/' + self.image_filename))
        else:
            return 'No Image'

    def max_level_from_stars(self, stars=None):
        if stars:
            return 10 + stars * 5
        else:
            return 10 + self.base_stars * 5

    def get_stats(self):
        from collections import OrderedDict

        start_grade = self.base_stars
        stats_list = OrderedDict()

        if self.is_awakened and self.base_stars > 1:
            start_grade -= 1

        for grade in range(start_grade, 7):
            max_level = self.max_level_from_stars(grade)

            # Add the actual calculated stats
            stats_list[str(grade)] = {
                'HP': self.actual_hp(grade, max_level),
                'ATK': self.actual_attack(grade, max_level),
                'DEF': self.actual_defense(grade, max_level),
            }

        return stats_list

    def actual_hp(self, grade, level):
        # Check that base stat exists first
        if not self.raw_hp:
            return None
        else:
            return self._calculate_actual_stat(self.raw_hp, grade, level) * 15

    def actual_attack(self, grade=base_stars, level=1):
        # Check that base stat exists first
        if not self.raw_attack:
            return None
        else:
            return self._calculate_actual_stat(self.raw_attack, grade, level)

    def actual_defense(self, grade=base_stars, level=1):
        # Check that base stat exists first
        if not self.raw_defense:
            return None
        else:
            return self._calculate_actual_stat(self.raw_defense, grade, level)

    @staticmethod
    def _calculate_actual_stat(stat, grade, level):
        # Magic multipliers taken from summoner's war wikia calculator. Used to calculate stats for lvl 1 and lvl MAX

bestiary/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse

from .filters import MonsterFilter
from .forms import FilterMonsterForm
from .models import Monster


def bestiary(request):
    name_search = request.GET.get('name-autocomplete')
    post_data = request.GET.copy()
    if name_search:
        post_data.update({'name': name_search})

    bestiary_filter_form = FilterMonsterForm(post_data or None)
    bestiary_filter_form.helper.form_action = reverse('bestiary:inventory')

    context = {
        'view': 'bestiary',
        'bestiary_filter_form': bestiary_filter_form,
        'init_load': True,
    }

    return render(request, 'bestiary/base.html', context)


def bestiary_inventory(request):
    context = _bestiary_inventory(request)
    return render(request, 'bestiary/inventory.html', context)


def _bestiary_inventory(request):
    name_search = request.GET.get('name-autocomplete')
    post_data = request.GET.copy()

    if name_search:
        post_data.update({'name': name_search})

    monster_queryset = Monster.objects.filter(obtainable=True).select_related('awakens_from', 'awakens_to', 'leader_skill').prefetch_related('skills')
    form = FilterMonsterForm(post_data or None)

    # Get queryset sort options
    sort_options = request.GET.get('sort')
    if sort_options:
        sort_col_match = {
            'name': 'name',
            'stars': 'base_stars',
            'element': 'element',
            'archetype': 'archetype',
            'awakens-to': 'awakens_to__name',
            'awakens-from': 'awakens_from__name',
            'leader-skill': 'leader_skill__amount',
            'hp-lv40': 'max_lvl_hp',
            'def-lv40': 'max_lvl_defense',
            'atk-lv40': 'max_lvl_attack',
            'spd': 'speed',
            'cri-rate': 'crit_rate',
            'cri-dmg': 'crit_damage',
            'res': 'resistance',
            'acc': 'accuracy',
            'skill-ups-reqd': 'skill_ups_to_max'
        }
        sort_direction_match = {
            'asc': '',
            'desc': '-',
        }
        sort_options = sort_options.split(';')
        sort_col = sort_col_match.get(sort_options[0])
        sort_direction = sort_direction_match.get(sort_options[1])

        if sort_col and sort_direction is not None:
            monster_queryset = monster_queryset.order_by(sort_direction + sort_col)

    if form.is_valid():
        monster_filter = MonsterFilter(form.cleaned_data, queryset=monster_queryset)
    else:
        monster_filter = MonsterFilter(queryset=monster_queryset)

    paginator = Paginator(monster_filter.qs, 100)
    page = request.GET.get('page')

    try:
        monsters = paginator.page(page)
    except PageNotAnInteger:
        monsters = paginator.page(1)
    except EmptyPage:
        monsters = paginator.page(paginator.num_pages)

    context = {
        'monsters': monsters,
        'page_range': paginator.page_range,
    }

    return context


def bestiary_detail(request, monster_slug):
    monster = Monster.objects.filter(bestiary_slug=monster_slug).first()

    if monster is None:
        raise Http404()

    mon = monster.base_monster
    monsters = []

    while mon is not None:
        monsters.append(mon)
        mon = mon.awakens_to

    context = {
        'view': 'bestiary',
        'active_slug': monster_slug,
        'family': monster.monster_family(),
        'monsters': monsters,
    }

    return render(request, 'bestiary/detail_base.html', context)

bestiary/templates/bestiary/base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load utils %}
{% load cache %}

{% block title %}Bestiary - {{ block.super }}{% endblock title %}

{% block content %}
    <div class="card shadow-sm border-0 mb-3">
        <div class="card-header bg-white">
            <button class="btn btn-outline-dark btn-block w-100 collapsed" data-bs-toggle="collapse" data-bs-target="#monsterFilterCollapse">
                <i class="fas fa-filter"></i> Filters
            </button>
        </div>
        <div class="card-body  collapse" id="monsterFilterCollapse">
            {% crispy bestiary_filter_form %}
        </div>
    </div>

    {% include 'bestiary/inventory.html' %}
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.24.6/js/widgets/widget-columnSelector.min.js"></script>
{% endblock javascript %}

{% block javascript_compressed %}
    <script type="text/javascript" src="{% static "bestiary/js/bestiary.js" %}"></script>
{% endblock javascript_compressed %}

bestiary/templates/bestiary/detail_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load utils %}
{% load cache %}

{% block title %}Bestiary - {{ monsters.0.get_element_display }} {{ monsters.0.name }}{% if monsters.0.can_awaken %} ({{ monsters.0.awakens_to.name }}){% endif %} - {{ block.super }}{% endblock title %}

{% block content %}
    {% static 'herders/images/' as img_url_prefix %}

    <div class="d-flex justify-content-center flex-wrap">
        {% for mon in family %}
            <div class="card border-0 shadow-sm mb-3 mx-3 p-0 card-monster card-dungeon-sm{% if mon.bestiary_slug == active_slug %} active{% endif %}">
                <div class="card-body  p-0">
                    <a href="{% url 'bestiary:detail' monster_slug=mon.bestiary_slug %}" class="nav-link p-3{% if mon.bestiary_slug == active_slug %} active{% endif %}">
                        <img class="monster-thumb" src="{{ img_url_prefix }}monsters/{{ mon.image_filename }}" loading="lazy" /> {{ mon }} {% if mon.is_awakened %}({{ mon.get_element_display }}){% endif %}
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr />

    {% for m in monsters %}
        {% include 'bestiary/monster_detail.html' with monster=m %}

        {% if monsters|length > 1 and not forloop.last %}<hr />{% endif %}
    {% endfor %}

{% endblock content %}

{% block javascript %}
<script src="https://code.highcharts.com/highcharts.js"></script>
{% endblock javascript %}

{% block javascript_compressed %}
    <script type="text/javascript" src="{% static "bestiary/js/bestiary.js" %}"></script>
{% endblock javascript_compressed %}

bestiary/templates/bestiary/essence_fragment.html
{% load staticfiles %}
{% static 'herders/images/' as img_url_prefix %}

<div class="element-essence" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-container="body" title="{{ element|capfirst }} {{ size|capfirst }}">
    <img src="{{ img_url_prefix }}items/essence_{{ element }}_{{ size }}.png" loading="lazy" />
    {% if not count == None %}<span class="image-plus image-plus-right">{{ count }}</span>{% endif %}
</div>

bestiary/templates/bestiary/inventory.html
{% load staticfiles %}
{% load utils %}

{% static 'herders/images/' as img_url_prefix %}
<div id="bestiary-inventory">
    <div class="card mb-3">
        <div class="card-header">
            <button class="btn btn-outline-dark column-select toggle collapsed" data-bs-toggle="collapse" data-bs-target="#column-selector-collapse">
                Select Columns
            </button>
            <div class="pagination float-right">
                <button class="page-item page-link border-0 pager-btnbg-light" {% if not monsters.has_previous %} disabled{% endif %} {% if monsters.has_previous %}data-page="{{ monsters.previous_page_number }}"{% endif %} aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </button>

                {% for page_num in page_range %}
                <button class="page-item page-link border-0 pager-btn bg-light{% if page_num == monsters.number %} active{% endif %}" data-page="{{ page_num }}" aria-label="Previous">
                    {{ page_num }}
                </button>
                {% endfor %}

                <button class="page-item page-link border-0 pager-btn bg-light" {% if not monsters.has_next %}disabled{% endif %} {% if monsters.has_next %}data-page="{{ monsters.next_page_number }}"{% endif %} aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </button>
            </div>
        </div>

        <div id="column-selector-collapse" class="collapse">
            <div class="card-body ">
                <div id="column-selectors" class="d-flex flex-wrap align-items-center justify-content-center"></div>
            </div>
        </div>

        {% if monsters|length %}
        <div class="table-responsive ">
            <table id="bestiary_table" class="table table-hover table-condensed monster-table " data-save-filters="false">
                <thead class="bg-white">
                    <tr>
                        <th data-sorter="false" data-columnSelector="disable"></th>
                        <th>Name</th>
                        <th>Stars</th>
                        <th>Element</th>
                        <th>Archetype</th>
                        <th>Awakens To</th>
                        <th>Awakens From</th>
                        <th>Leader Skill</th>
                        <th data-sorter="false">Skills</th>
                        <th data-columnSelector="false">Skill-Ups</th>
                        <th data-columnSelector="false">HP (Lv.40)</th>
                        <th data-columnSelector="false">DEF (Lv.40)</th>
                        <th data-columnSelector="false">ATK (Lv.40)</th>
                        <th data-columnSelector="false">SPD</th>
                        <th data-columnSelector="false">CRI Rate</th>
                        <th data-columnSelector="false">CRI Dmg</th>
                        <th data-columnSelector="false">RES</th>
                        <th data-columnSelector="false">ACC</th>
                        <th data-sorter="false" data-columnSelector="false">Awakening Materials</th>
                    </tr>
                </thead>
                <tbody>
                    {% for monster in monsters %}
                    <tr class="">
                        <td class="monster-image">
                            <a href="{% url 'bestiary:detail' monster_slug=monster.bestiary_slug %}">
                                {% include 'bestiary/monster/portrait_small.html' with monster=monster only %}
                            </a>
                        </td>
                        <td><a href="{% url 'bestiary:detail' monster_slug=monster.bestiary_slug %}">{{ monster.name|title }}</a></td>
                        <td>{{ monster.base_stars }}<i class="fas fa-star"></i></td>
                        <td class="monster-element">
                            <img src="{{ img_url_prefix }}elements/{{ monster.element }}.png" class="monster-element" loading="lazy" />
                            <span class="visually-hidden">{{ monster.element }}</span>
                        </td>
                        <td class="monster-type">{{ monster.get_archetype_display }}</td>
                        <td class="monster-awakens">
                            {% if monster.awakens_to %}
                            <a href="{% url 'bestiary:detail' monster_slug=monster.awakens_to.bestiary_slug %}">
                                <img src="{{ img_url_prefix }}monsters/{{ monster.awakens_to.image_filename }}" class="monster-thumb" loading="lazy" /> {{ monster.awakens_to.name|title }}
                            </a>
                            {% endif %}
                        </td>
                        <td class="monster-awakens">
                            {% if monster.awakens_from %}
                            <a href="{% url 'bestiary:detail' monster_slug=monster.awakens_from.bestiary_slug %}">
                                <img src="{{ img_url_prefix }}monsters/{{ monster.awakens_from.image_filename }}" class="monster-thumb" loading="lazy" /> {{ monster.awakens_from.name|title }}
                            </a>
                            {% endif %}
                        </td>
                        <td class="monster-leader-skill">
                            {% if monster.leader_skill %}
                                <div>
                                    <img src="{{ img_url_prefix }}skills/leader/{{ monster.leader_skill.icon_filename }}" loading="lazy" 
                                         data-bs-toggle="popover" data-bs-trigger="hover" data-bs-placement="top" data-bs-container="body" title="Leader Skill" data-bs-content="{{ monster.leader_skill.skill_string }}" />
                                    <span class="image-plus image-plus-top-left">{{ monster.leader_skill.amount }}%</span>
                                    <span class="visually-hidden">
                                        {{ monster.leader_skill.get_attribute_display }}
                                        {{ monster.leader_skill.get_area_display }}
                                    </span>
                                </div>
                            {% endif %}
                        </td>
                        <td class="monster-awaken-materials">
                            <div class="d-flex">
                            {% for skill in monster.skills.all %}
                                <div class="monster-skill-thumb pull-left skill-popover" data-skill-id="{{ skill.pk }}" title="{{ skill.name }}" data-bs-placement="top">
                                    <img src="{{ img_url_prefix }}skills/{{ skill.icon_filename }}" loading="lazy" />
                                    {% if skill.max_level > 1 %}<span class="image-plus image-plus-right">{{ skill.max_level }}</span>{% endif %}
                                </div>
                            {% endfor %}
                            </div>
                        </td>
                        <td>
                            {% if monster.skill_ups_to_max > 0 %}
                            <div class="monster-image">
                                <img src="{{ img_url_prefix }}monsters/devilmon_dark.png" class="monster-thumb" loading="lazy" />
                                <span class="image-plus image-plus-main">{{ monster.skill_ups_to_max }}</span>
                            </div>
                            {% else %}
                            <span class="glyphicon glyphicon-ok-circle text-success"></span>
                            {% endif %}
                        </td>
                        <td>{{ monster.max_lvl_hp }}</td>
                        <td>{{ monster.max_lvl_defense }}</td>
                        <td>{{ monster.max_lvl_attack }}</td>
                        <td>{{ monster.speed }}</td>
                        <td>{{ monster.crit_rate }}%</td>
                        <td>{{ monster.crit_damage }}%</td>
                        <td>{{ monster.resistance }}%</td>
                        <td>{{ monster.accuracy }}%</td>
                        <td class="monster-awaken-materials">
                            {% if monster.can_awaken and not monster.is_awakened %}
                                {% include 'bestiary/awakening_essences.html' with monster=monster only %}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% elif init_load %}
            <div class="card-body "></div>
        {% else %}
        <div class="card-body ">
            <div class="callout callout-warning"><h2>No results!</h2>Looks like there's nothing to show...</div>
        </div>
        {% endif %}
        <div class="card-footer ">
            <div class="pagination float-right">
                <button class="page-item page-link border-0 pager-btn bg-light" {% if not monsters.has_previous %} disabled{% endif %} {% if monsters.has_previous %}data-page="{{ monsters.previous_page_number }}"{% endif %} aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </button>

                {% for page_num in page_range %}
                <button class="page-item page-link border-0 pager-btn bg-light{% if page_num == monsters.number %} active{% endif %}" data-page="{{ page_num }}" aria-label="Previous">
                    {{ page_num }}
                </button>
                {% endfor %}

                <button class="page-item page-link border-0 pager-btn bg-light" {% if not monsters.has_next %}disabled{% endif %} {% if monsters.has_next %}data-page="{{ monsters.next_page_number }}"{% endif %} aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </button>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>