api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'bestiary', views.MonsterViewSet)
router.register(r'skill', views.MonsterSkillViewSet)
router.register(r'skill_effect', views.MonsterSkillEffectViewSet)
router.register(r'leader_skill', views.MonsterLeaderSkillViewSet)
router.register(r'source', views.MonsterSourceViewSet)

urlpatterns = [
    # REST framework stuff
    url(r'^', include(router.urls)),

    # Custom API stuff
    url(r'bestiary/(?P<pk>[0-9]+)/chart/$', views.bestary_stat_charts, name='bestiary_stat_chart'),
]

bestiary/urls.py
from django.urls import path, include

from . import views

app_name = 'bestiary'

urlpatterns = [
    path('', views.bestiary, name='home'),
    path('inventory/', views.bestiary_inventory, name='inventory'),
    path('<slug:monster_slug>/', views.bestiary_detail, name='detail'),
]

swarfarm/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles import views
from bestiary.autocomplete import *

urlpatterns = [
    # AJAX-y stuff first
    url(r'^autocomplete/', include([
        url(r'^bestiary/$', BestiaryAutocomplete.as_view(), name='bestiary-monster-autocomplete'),
        url(r'^quick-search/$', QuickSearchAutocomplete.as_view(), name='bestiary-quicksearch-autocomplete'),
    ])),
    url(r'^api/v2/', include('apiv2.urls', namespace='v2')),
    url(r'^api/', include('api.urls')),
    url(r'^api(/v\d+)?/auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Bestiary
    url(r'^bestiary/', include('bestiary.urls', namespace='bestiary')),

    # SWARFARM app
    url(r'^', include('news.urls', namespace='news')),

    # Django auth/admin stuff
    url('admin/clearcache/', include('clearcache.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

data_log/models.py
from datetime import datetime, timedelta

import pytz
from django.contrib.postgres.fields import JSONField
from django.db import models

from bestiary.models import Monster, Dungeon, Level, GameItem, Rune, RuneCraft
from herders.models import Summoner


# Abstract models for encapsulating common data like drops and log entry metadata
class LogEntry(models.Model):
    # Abstract model with basic fields required for logging anything

    TIMEZONE_SERVER_MAP = {
        'America/Los_Angeles': Summoner.SERVER_GLOBAL,
        'Europe/Berlin': Summoner.SERVER_EUROPE,
        'Asia/Seoul': Summoner.SERVER_KOREA,
        'Asia/Shanghai': Summoner.SERVER_ASIA,
    }

    wizard_id = models.BigIntegerField()
    summoner = models.ForeignKey(Summoner, on_delete=models.SET_NULL, blank=True, null=True)
    timestamp = models.DateTimeField(blank=True, null=True)
    server = models.IntegerField(choices=Summoner.SERVER_CHOICES, null=True, blank=True)

    class Meta:
        abstract = True
        ordering = ('-timestamp', '-pk')
        get_latest_by = 'timestamp'

    def parse_common_log_data(self, log_data):
        self.wizard_id = log_data['request']['wizard_id']
        self.server = LogEntry.TIMEZONE_SERVER_MAP.get(log_data['response']['tzone'])
        self.timestamp = datetime.fromtimestamp(log_data['response']['tvalue'], tz=pytz.timezone('GMT'))


class ItemDropManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.prefetch_related('item')


class ItemDrop(models.Model):
    PARSE_KEYS = (
        # For when drops are in a key: value format from game API
        'mana',
        'energy',
        'crystal',
    )

    PARSE_ITEM_TYPES = (
        # For when drops have a master_item_id and master_item_type specified
        GameItem.CATEGORY_CURRENCY,
        GameItem.CATEGORY_SUMMON_SCROLL,
        GameItem.CATEGORY_ESSENCE,
        GameItem.CATEGORY_CRAFT_STUFF,
    )

    RELATED_NAME = 'items'
    objects = ItemDropManager()

    item = models.ForeignKey(GameItem, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.item} x{self.quantity}'

    @classmethod
    def parse(cls, **kwargs):
        key = kwargs.get('key')
        val = kwargs.get('val')
        master_type = kwargs.get('item_master_type') or kwargs.get('type')
        master_id = kwargs.get('item_master_id') or kwargs.get('id')

        if key and val is not None:
            # Dungeon drop parsing
            if key == 'mana':
                item = GameItem.objects.get(category=GameItem.CATEGORY_CURRENCY, name='Mana')
                quantity = val
            elif key == 'energy':
                item = GameItem.objects.get(category=GameItem.CATEGORY_CURRENCY, name='Energy')
                quantity = val
            elif key == 'crystal':
                item = GameItem.objects.get(category=GameItem.CATEGORY_CURRENCY, name='Crystal')
                quantity = val
            else:
                raise ValueError(f"Can't parse item type {key} with {cls.__name__}")
        elif master_type and master_id:
            # type and ID parsing
            quantity = kwargs.get('amount') or kwargs.get('item_quantity') or kwargs.get('quantity')

            if quantity is None:
                raise ValueError('Quantity not found')

            if master_type not in cls.PARSE_ITEM_TYPES:
                raise ValueError(f"Can't parse item type {master_type} with {cls.__name__}")

            item = GameItem.objects.get(category=master_type, com2us_id=master_id)
        else:
            raise ValueError('Must specify either (key, val) kwargs or (item_master_type, item_master_id, quantity) kwargs')

        if item and quantity:
            log_item = cls(
                item=item,
                quantity=quantity,
            )
            return log_item


class MonsterDropManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.prefetch_related('monster')


class MonsterDrop(models.Model):
    PARSE_ITEM_TYPES = (
        GameItem.CATEGORY_MONSTER,
        GameItem.CATEGORY_RAINBOWMON,
    )

    RELATED_NAME = 'monsters'
    objects = MonsterDropManager()

    monster = models.ForeignKey(Monster, on_delete=models.PROTECT)
    grade = models.IntegerField()
    level = models.IntegerField()

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.monster} {self.grade}* lv.{self.level}'

    @classmethod
    def parse(cls, **monster_info):
        com2us_id = monster_info.get('unit_master_id') or monster_info.get('item_master_id')
        grade = monster_info.get('class') or monster_info.get('unit_class')
        level = monster_info.get('unit_level') or 1
        return cls(
                monster=Monster.objects.get(com2us_id=com2us_id),
                grade=grade,
                level=level,
            )


class MonsterPieceDrop(models.Model):
    PARSE_KEYS = ()

    RELATED_NAME = 'monster_pieces'
    objects = MonsterDropManager()

    monster = models.ForeignKey(Monster, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.monster} x{self.quantity}'


class RuneDrop(Rune):
    PARSE_ITEM_TYPES = (
        GameItem.CATEGORY_RUNE,
    )

    RELATED_NAME = 'runes'

    class Meta:
        abstract = True

    @classmethod
    def parse(cls, **rune_data):
        rune_set = cls.COM2US_TYPE_MAP[rune_data['set_id']]
        original_quality = cls.COM2US_QUALITY_MAP[rune_data['extra']]
        main_stat = cls.COM2US_STAT_MAP[rune_data['pri_eff'][0]]
        main_stat_value = rune_data['pri_eff'][1]
        innate_stat = cls.COM2US_STAT_MAP.get(rune_data['prefix_eff'][0])
        innate_stat_value = rune_data['prefix_eff'][1] if innate_stat else None

        substats = []
        substat_values = []

        for sub, sub_val, *rest in rune_data['sec_eff']:
            substats.append(cls.COM2US_STAT_MAP[sub])
            substat_values.append(sub_val)

        return cls(
            type=rune_set,
            stars=rune_data['class'],
            level=rune_data['upgrade_curr'],
            slot=rune_data['slot_no'],
            original_quality=original_quality,
            value=rune_data['sell_value'],
            main_stat=main_stat,
            main_stat_value=main_stat_value,
            innate_stat=innate_stat,
            innate_stat_value=innate_stat_value,
            substats=substats,
            substat_values=substat_values,
        )


class RuneCraftDrop(RuneCraft):
    PARSE_KEYS = ()
    PARSE_ITEM_TYPES = (
        GameItem.CATEGORY_RUNE_CRAFT,
    )

    RELATED_NAME = 'rune_crafts'

    class Meta:
        abstract = True

    @classmethod
    def parse(cls, **craft_data):
        craft_type_id = str(craft_data.get('craft_type_id') or craft_data.get('runecraft_item_id'))
        craft_type = craft_data.get('craft_type') or craft_data.get('runecraft_type')

        return cls(
            type=cls.COM2US_CRAFT_TYPE_MAP[craft_type],
            rune=cls.COM2US_TYPE_MAP[int(craft_type_id[:-4])],
            quality=cls.COM2US_QUALITY_MAP[int(craft_type_id[-1:])],
            stat=cls.COM2US_STAT_MAP[int(craft_type_id[-4:-2])],
        )


# Data gathering model to store game API data for development and debugging purposes
class FullLog(LogEntry):
    command = models.TextField(max_length=150, db_index=True)
    request = JSONField()
    response = JSONField()

    @classmethod
    def parse(cls, summoner, log_data):
        log_entry = cls(summoner=summoner)
        log_entry.parse_common_log_data(log_data)
        log_entry.command = log_data['request']['command']
        log_entry.request = log_data['request']
        log_entry.response = log_data['response']
        log_entry.save()


# Magic Shop
class ShopRefreshLogManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related(
            ShopRefreshItemDrop.RELATED_NAME,
            ShopRefreshRuneDrop.RELATED_NAME,
            ShopRefreshMonsterDrop.RELATED_NAME,
        )


class ShopRefreshLog(LogEntry):
    objects = ShopRefreshLogManager()

    slots_available = models.IntegerField(blank=True, null=True)

    @classmethod
    def parse_shop_refresh(cls, summoner, log_data):
        if log_data['response']['market_info']['update_remained'] != 3600:
            # Ignore any log that does not have the full hour of refresh time indicating it is brand new.
            return

        log = cls(summoner=summoner)
        log.parse_common_log_data(log_data)
        log.slots_available = log_data['response']['market_info']['open_slots']
        log.save()

        log.parse_items_for_sale(log_data['response']['market_list'])

    def parse_items_for_sale(self, sale_items):
        for item in sale_items:
            master_type = item['item_master_type']

            if master_type in ShopRefreshItemDrop.PARSE_ITEM_TYPES:
                item_log = ShopRefreshItemDrop.parse(**item)
            elif master_type in ShopRefreshRuneDrop.PARSE_ITEM_TYPES:
                item_log = ShopRefreshRuneDrop.parse(**item)
            elif master_type in ShopRefreshMonsterDrop.PARSE_ITEM_TYPES:
                item_log = ShopRefreshMonsterDrop.parse(**item)
            else:
                raise ValueError(f"Don't know how to parse {master_type} in {self.__class__.__name__}")

            if item_log:
                item_log.log = self
                item_log.save()


class ShopRefreshDrop(models.Model):
    cost = models.IntegerField()

    class Meta:
        abstract = True

    @classmethod
    def parse(cls, **kwargs):
        log = super().parse(**kwargs)
        log.cost = kwargs.get('buy_mana', 0)
        return log


class ShopRefreshItemDrop(ShopRefreshDrop, ItemDrop):

herders/templates/herders/profile/data_logs/rift_beast.html
{% extends 'herders/profile/data_logs/base.html' %}
{% load utils humanize %}

{% block title %}
    Elemental Rift Beast - {{ block.super }}
{% endblock %}

{% block logs %}
<table class="table table-striped table-condensed">
<thead>
<tr>
    <th>Timestamp</th>
    <th>Dungeon</th>
    <th>Grade</th>
    <th>Total Damage</th>
    <th>Success</th>
    <th>Clear Time</th>
    <th>Drops</th>
</tr>
</thead>
<tbody>
{% for log in logs %}
    <tr>
        <td>{{ log.timestamp }}</td>
        <td>{{ log.level.dungeon }}</td>
        <td>{{ log.get_grade_display }}</td>
        <td>{{ log.total_damage|intcomma }}</td>
        <td>
            {% if log.success %}
                <span class="glyphicon glyphicon-ok text-success"></span>
            {% else %}
                <span class="glyphicon glyphicon-remove text-danger"></span>
            {% endif %}
        </td>
        <td>{{ log.clear_time|timedelta }}</td>
        <td>{% include './drops/all_drops.html' %}</td>
    </tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

herders/templates/herders/profile/data_logs/summons.html
{% extends 'herders/profile/data_logs/base.html' %}
{% load static utils humanize %}

{% block title %}
    Summons - {{ block.super }}
{% endblock %}

{% block logs %}
    {% static 'herders/images/' as img_url_prefix %}

    <table class="table table-striped table-condensed">
    <thead>
    <tr>
        <th>Timestamp</th>
        <th>Method</th>
        <th>Monster</th>
    </tr>
    </thead>
    <tbody>
    {% for log in logs %}
        <tr>
            <td>{{ log.timestamp }}</td>
            <td>
                <div class="monster-image" data-toggle="tooltip" data-placement="top" title="{{ log.item.name }}">
                    <img src="{{ img_url_prefix }}items/{{ log.item.icon }}" class="monster-thumb"/>
                </div>
            </td>
            <td>
                <a href="{% url 'bestiary:detail' monster_slug=log.monster.bestiary_slug %}" class="monster-image" data-toggle="tooltip" data-placement="top" title="{{ log.monster.get_element_display }} {{ log.monster.name }}">
                    <div>
                        <img src="{{ img_url_prefix }}monsters/{{ log.monster.image_filename }}" class="monster-thumb"/>
                        <span>
                            {% for x in log.grade|get_range %}
                                {% if log.monster.is_awakened %}
                                    <img src="{{ img_url_prefix }}stars/star-awakened.png" class="monster-star monster-star-{{ forloop.counter }}" />
                                {% elif log.monster.can_awaken %}
                                    <img src="{{ img_url_prefix }}stars/star-unawakened.png" class="monster-star monster-star-{{ forloop.counter }}" />
                                {% else %}
                                    <img src="{{ img_url_prefix }}stars/star-fodder.png" class="monster-star monster-star-{{ forloop.counter }}" />
                                {% endif %}
                            {% endfor %}
                        </span>
                    </div>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}